
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acujkaigqvbqbckitwyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjdWprYWlncXZicWJja2l0d3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3OTM3NDIsImV4cCI6MjA2MzM2OTc0Mn0.y57GkDvmfOV1KY8Tz5HR1o57sQUo1k3di2hxP5NjLbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
